name: Build, Deploy, and Update EKS Cluster

on:
  push

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set Build Number
      id: build-number
      run: echo "BUILD_NUMBER=$(date +'%Y%m%d%H%M%S')-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t public.ecr.aws.com/q1h1b7r6/nginx:${BUILD_NUMBER} .

    - name: Login to Amazon ECR
      id: login-ecr
      run: echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} | docker login -u ${{ secrets.AWS_USER_ACCESS_KEY }} --password-stdin public.ecr.aws.com/q1h1b7r6

    - name: Push image
      run: docker push public.ecr.aws.com/q1h1b7r6/nginx:${BUILD_NUMBER}

   
